### PR TITLE
style(cardcareers): reduce bottom padding

### PR DESCRIPTION
**Pull request by Wotusay**
before:
image

after:
image

### CODE REVIEW

**Comment by darenmalfait** [comment]
this issue is about the inside of the card. My bad, I should have used screenshots.

**Comment by Wotusay** [comment]
Before:
image

After:
image

**Comment by darenmalfait** [comment]
merge conflicts probably because #135 got merged

**Comment by Wotusay** [comment]
Should be fixed now!

**Comment by Wotusay** [comment]
Its now he right version the [b06a39a](https://github.com/rightinyourwheelhouse/wheelhouse-website/pull/138/commits/b06a39add78d19db99a0098c908a9f7a4d17c7f2) commit would have deleted the #135. But now it should be fine

**Review by darenmalfait — APPROVED** [review]

**Pull request merged**
